### ISSUE TITLE
google.maps.event.trigger(mapname, 'resize')

### ISSUE THREAD

**Issue by florianbepunkt** [benhuson/WP-Geo#64] opened 2014-11-17 12:19 UTC
Thank you for the nice plugin. I wneed to trigger a resize / redraw of the map since I want to place it inside a tab.

How can if get the mapname of a certain map I want to show (inside the loop)?

Thanks
Florian

**Comment by ssuess** [comment] 2015-03-12 14:57
Thanks, I am in the same boat as you. Using your code, I was able to get the map to redraw in my hidden div, but it is not centered. Although I can retrieve the center coords, setCenter fails to correctly set it. Did you have any luck fixing it?

**Comment by ssuess** [comment] 2015-03-12 15:07
oh I just solved it! the reason the center would not set properly is because I was using the var "center" which it seems must be defined elsewhere. Once I replaced it with a different one (centerofmap) it worked! Here is my code in case it helps you or anyone:

           jQuery('#my_slider_trigger').click(function(e) {
           var map_id = window[jQuery('div.wpgeo_map').attr('id')];
            jQuery('#my_slider_div').slideToggle(400);
            jQuery('#my_slider_trigger').toggleClass('open');
            jQuery(window).trigger('resize');
            var centerofmap = map_id.getCenter(); 
            google.maps.event.trigger(map_id, 'resize'); 
            map_id.setCenter(centerofmap);
            });

**Comment by florianbepunkt** [comment] 2015-03-12 16:16
Thanks a lot! I hadn't solved the center issue myself yet. So this is much
appreciated! Kind regards, Florian

**Comment by ssuess** [comment] 2015-03-12 16:41
Glad we were able to help each other out! :)

**Comment by benhuson** [comment] 2015-06-10 08:12
@florianbepunkt @ssuess Thanks for you're work on this.

I'm closing this ticket as a duplicate of #68 which now has a pull request for a helper JavaScript function which I'll release in the next version of the plugin which will make triggering a map refresh easier.

**Closed by benhuson** 2015-06-10 08:12 UTC
